### ISSUE TITLE
Multiple videos with endcards?

### ISSUE THREAD

**Issue by yenning** [theonion/videojs-endcard#5]
Hi,
Thank you very much for this feature. I have more than one videos on a player (using tabs, no autoplay) and would like to have endcards at the end of each video. Is it possible that I can do that?

That reason why I want to have endcard on each video because my videos are used for the purpose of product tutorials. We'd like to put links on endcards to specific forum topics and documentation so our users have the option of acquiring more info after watching the videos.

Thank you,
Yen-Ning

**Comment by shaqq** [comment]
It sounds like you have a specific implementation of videojs, in which case you'd have to fork this repo and configure it to how you're setting up your video tutorials.

The endcard is added when the "ended" event is fired. So, as long as that corresponds with when you want the endcard to appear, that should work. Otherwise, you'd have to change it.

**Comment by yenning** [comment]
Thank you for the reply. I followed the example and it worked for just a single video.

I am not a javascript expert so please bear with me. 
For each video, I have different ids, for example:
video id=video-1
video id=video-2
video id=video-3
...etc

I noticed that if I change the video id to "video", the endcard on that specific video works. But only on that one. If I were to have endcard on each singe video, I need to make some changes on the following line?

var video = videojs('video');

Thank you.

**Comment by shaqq** [comment]
Hasn't been updated in a while - see my previous comment. We only support the base implementation of videojs with a single video.
